[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'gcc', 'gnumake', 'pkg-config', 'systemd.dev']

[phases.install]
cmds = ['cd frontend && npm install']

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'cd frontend && npm run start'
