[workspace]
members = [
    "programs/x402_protocol"
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = true
codegen-units = 1
